---
title: "Descriptive analysis of CDR3 data"
output:
  html_document:
      keep_md: true
  html_notebook: default
---

```{r}
library(tidyverse); library(vroom)
```

### Load in Imrep CDR3 data
```{r}
df <- vroom("/labs/khatrilab/solomonb/201912111345.csv") 
```

### Number of unqique CDR3 sequences

**For all antigen receptor chains**
```{r}
df %>% 
  mutate(chain_cdr3 = paste(Chain_type, CDR3_AA_Seq, sep ="_")) %>% 
  summarise(unique_cdr3 = length(unique(chain_cdr3)), 
            total_reads = sum(Read_count), 
            total_sra = length(unique(sra))) %>% 
  mutate(reads_per_cdr3 = total_reads/unique_cdr3,
          cdr3_per_sra = unique_cdr3/total_sra,
          reads_per_sra = total_reads/total_sra) %>% 
  mutate_if(is.numeric, 
                function(x) ifelse(x >= 10000, 
                                   scales::scientific_format(digits = 3)(round(x)), 
                                   round(x)))
```

**By antigen receptor chain groups**
```{r}
df %>% 
  group_by(Chain_type) %>% 
  summarise(unique_cdr3 = length(unique(CDR3_AA_Seq)), 
            total_reads = sum(Read_count), 
            total_sra = length(unique(sra))) %>% 
  mutate(reads_per_cdr3 = total_reads/unique_cdr3,
          cdr3_per_sra = unique_cdr3/total_sra,
          reads_per_sra = total_reads/total_sra) %>% 
  mutate_if(is.numeric, 
                function(x) ifelse(x >= 10000, 
                                   scales::scientific_format(digits = 3)(round(x)), 
                                   round(x)))
```


### Number of reads per sample

```{r}
df.summary <- df %>% 
  group_by(sra, Chain_type) %>% 
  summarise(reads = sum(Read_count), sequences = length(Read_count)) %>%  
  mutate(reads_per_sequence = reads/sequences)
# df.thresh <- df.cdr3Count %>% filter(n > 100)
df.summary %>% 
  ggplot(aes(x = Chain_type, y  = log10(reads))) +
  geom_jitter(size = 0.1, alpha = 0.1, color = "lightblue")+
  geom_violin(scale = "width", size = 1, fill = NA)+
  theme_classic() +
  ggtitle("CDR3 reads per sample")
```

### Number of unique CDR3s per sample

```{r}
df.summary %>% 
  ggplot(aes(x = Chain_type, y  = log10(sequences))) +
  geom_jitter(size = 0.1, alpha = 0.1, color = "lightblue")+
  geom_violin(scale = "width", size = 1, fill = NA)+
  theme_classic()+
  ggtitle("Unique CDR3 sequences per sample")
```

### Number of reads per unique CDR3 

```{r}
df.summary %>% 
  ggplot(aes(x = Chain_type, y  = log10(reads_per_sequence))) +
  geom_jitter(size = 0.1, alpha = 0.1, color = "lightblue")+
  geom_violin(scale = "width", size = 1, fill = NA)+
  theme_classic()+
  ggtitle("Reads per unique CDR3 sequence per sample")
```